version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: slms_postgres
    environment:
      POSTGRES_USER: erenb
      POSTGRES_PASSWORD: Password12
    ports:
      - "5434:5432"
    volumes:
      - slms-postgres_data:/var/lib/postgresql/data
    networks:
      - slms_network
       
  rabbitmq:
    image: rabbitmq:3-management
    container_name: slms_rabbitmq
    ports:
      - "5673:5672"   # Mesajlaşma Portu (Uygulama içi)
      - "15673:15672" # Yönetim Paneli (Tarayıcıdan erişim)
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - slms-rabbitmq_data:/var/lib/rabbitmq
    networks:
      - slms_network
  
  advisor.api:
    build:
      context: .
      dockerfile: Advisor.API/Dockerfile
    container_name: slms_advisor_service
    ports:
        - "5053:8080"
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=AdvisorDb;Username=erenb;Password=Password12
        - ConnectionStrings__RabbitMq=rabbitmq://guest:guest@rabbitmq:5672
        - ServiceUrls__StudentApi=http://student.api:8080
    depends_on:
        - postgres
        - rabbitmq
    networks:
        - slms_network

  identity.api:
    build:
      context: .
      dockerfile: Identity.API/Dockerfile
    container_name: slms_identity_service
    ports:
      - "5294:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=IdentityDb;Username=erenb;Password=Password12
      - ConnectionStrings__RabbitMq=rabbitmq://guest:guest@rabbitmq:5672
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - slms_network

  lecture.api:
    build:
      context: .
      dockerfile: Lecture.API/Dockerfile
    container_name: slms_course_service
    ports:
      - "5119:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=LectureDb;Username=erenb;Password=Password12
      - ConnectionStrings__RabbitMq=rabbitmq://guest:guest@rabbitmq:5672
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - slms_network

  student.api:
    build:
      context: .
      dockerfile: Student.API/Dockerfile
    container_name: slms_student_service
    ports:
      - "5217:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=StudentDb;Username=erenb;Password=Password12
      - ConnectionStrings__RabbitMq=rabbitmq://guest:guest@rabbitmq:5672
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - slms_network

volumes:
  slms-postgres_data:
  slms-rabbitmq_data:

networks:
  slms_network:
    driver: bridge